### ISSUE TITLE
Typed.js V3 Roadmap

### ISSUE THREAD

**Issue by mattboldt** [mattboldt/typed.js#441]
Hello all! Planning V3 of Typed.js currently, and I could use your help! I'm setting up a project board at the moment but this is my first time using it so I'm figuring out how it works. https://github.com/mattboldt/typed.js/projects/1

Here's what kicked off my desire to update: https://github.com/mattboldt/typed.js/pull/92. This PR was added on May 31, 2015. 2015! Nearly 5 years ago! I honestly don't remember why it was never merged, and for that I want to apologize to @tameemsafi.

Furthermore, I checked out Tameem's terrific library, https://github.com/tameemsafi/typewriterjs. I absolutely love how he achieved the effect, his code is very pleasant to read, and its performance is miles ahead of Typed.js. His work is incredibly inspiring, and I suggest anyone looking to learn about authoring a library go check it out. Awesome work, @tameemsafi.

### About the rewrite

One huge thing TypewriterJS has that Typed.js doesn't: usage of `requestAnimationFrame` instead of `setTimeout` or `setInterval`. This new(ish) feature couldn't be more perfect for a typing effect, and I'm excited to implement it. Of course, since Typed.js V3 will be heavily inspired by TypewriterJS, I plan on crediting Tameem wherever possible, and linking his library in my main README. Tameem, if you're reading this, please reach out and let me know your thoughts (me@mattboldt.com)

#### Why have both libraries if they do the same thing?

Well, competition is always good. And I consider it a form of competition because, while this software is open source, it doesn't mean our work doesn't provide value to us, the authors, in other ways. Contributions to OSS looks good on a resume, and I'd be lying if I said Typed.js never helped me land a job. As such, I think mine and other similar libraries must continue to coexist for the betterment of everyone. Because Typed.js has so much traffic and stars, I understand it will be chosen for that fact alone in many cases v.s. alternatives. Because of this, I'm adamant about including Tameem's library at the very top of my README (in addition to anything we discuss).

## TODO

- [ ] Implement `requestAnimationFrame` and a queue-based event system
- [ ] Migrate to `TypeScript`
- [ ] Add a test suite (considering Jest or Mocha)
- [ ] Heavy focus on better docs (I suspect TypeScript will aid in this effort)
- [ ] Built-in support for React, Vue, and more
  - @Orlandster has done some great work on this in his wrapper library, https://github.com/Orlandster/vue-typed-js. If you're able to, Orlando, I've love for you to work on the Vue implementation of V3.
- [ ] Built-in accessibility
  - The "SEO friendly" feature of typed _sort of_ touches on this area, but not nearly enough. I suspect screen reader users experiencing Typed.js are confused by how the content is structured, and I aim to solve that by automatically generating more accessible text content, as well as providing best practice examples in the docs. 
- [ ] Reorganize more advanced features
  - I mentioned in https://github.com/mattboldt/typed.js/pull/432#issuecomment-558765619 that I don't like having too much advanced syntax inside the content itself. Using `^`, `~`, just isn't very intuitive and I believe this can be replaced by the chain structure.
- [ ] Callback hell
  - Typed.js has too many unique callback options. Instead, callbacks should be implemented as part of the chain.
- [ ] Add highlight-to-erase feature

If you made it this far, thanks for sticking around! Please reply to this thread with any questions or ideas.

**Comment by j-funk** [comment]
These are great, how is it coming along?
